project:
  type: website
  output-dir: docs

website:
  title: "Biología del Desarrollo y Plasticidad Neural-BIODEN"
  navbar:
    background: dark
    search: true
    left:
      - href: index.qmd
        text: Inicio
      - href: https://sites.google.com/unicauca.edu.co/bioden/integrantes
        text: Integrantes
      - href: https://sites.google.com/unicauca.edu.co/bioden/eventos/webinar-neurolab
        text: Webinar Neurolab
      - href: https://sites.google.com/unicauca.edu.co/bioden/material-educativo
        text: Material educativo
      - href: https://sites.google.com/unicauca.edu.co/bioden/eventos
        text: Eventos
      - href: https://sites.google.com/unicauca.edu.co/bioden/bolet%C3%ADn
        text: Boletín Bioden
      - href: https://sites.google.com/unicauca.edu.co/bioden/contacto
        text: Contacto
    right: 
      - icon: instagram
        href: https://www.instagram.com/dbg_unicauca/
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61583453722433
      
        
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

