project:
  type: website
  output-dir: docs

website:
  title: "BIODEN"
  favicon: 'logo.png'
  cookie-consent: 
    type: express
    style: interstitial
    palette: dark
  navbar:
    background: light
    logo: logo.png
    search: true
    left:
      - href: index.qmd
        text: Inicio
      - href: integrantes.qmd
        text: Integrantes
      - href: https://sites.google.com/unicauca.edu.co/bioden/webinar-neurolab
        text: Webinar Neurolab
      - href: material_educativo.qmd
        text: Material educativo
      - href: https://sites.google.com/unicauca.edu.co/bioden/eventos
        text: Eventos
      - href: https://sites.google.com/unicauca.edu.co/bioden/bolet%C3%ADn-bioden
        text: Boletín Bioden
      - href: https://sites.google.com/unicauca.edu.co/bioden/contacto
        text: Contacto
      - href: https://sites.google.com/unicauca.edu.co/bioden/solicitudes
        text: Solicitudes
    right: 
      - icon: instagram
        href: https://www.instagram.com/dbg_unicauca/
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61583453722433
      - icon: envelope
        href: mailto:bioden@unicauca.edu.co
    collapse: true
    reader-mode: true
    toc: true
  page-footer:
    left: |
      Semillero de Biología del Desarrollo y Plasticidad Neural © 2025. All content licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). 
      Sitio web desarrollado por Xavier Clemente García Cevallos y Diego Fernando Dueñas Paz

    center: 
      - icon: github
        href: https://github.com/xavierclementegarcia
      - icon: envelope
        href: mailto:bioden@unicauca.edu.co
    right: |
      Made with <a href="https://www.r-project.org/"><img src="https://www.r-project.org/Rlogo.png" alt="R" width="25px"></a> 
      and <a href="https://quarto.org/"><img src="https://quarto.org/quarto.png" alt="Quarto" width="65px"></a>.
        

format:
  html:
    margin-header: |
      ![Universidad del Cauca](/logos/unicauca.png)
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    code-overflow: scroll
    anchor-sections: false

editor: visual

